# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from pyqt5_utilities import *


# class Ui_MainWindow(object):

class MyMainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit.setGeometry(QtCore.QRect(400, 30, 271, 26))
        self.line_edit.setObjectName("line_edit")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(680, 30, 95, 27))
        self.browse_button.setObjectName("browse_button")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        # self.browse_button.clicked.connect(lambda: browse_file(self))
        self.browse_button.clicked.connect(lambda: browse(self))


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browse_button.setText(_translate("MainWindow", "Browse"))

    # LOGIC
    def local_browse(self):
        ui_file, _ = QFileDialog.getOpenFileName(self, "Select .ui File", "", "UI Files (*.ui)")
        if ui_file:
            self.ui_path_edit.setText(ui_file)

    def convert(self):
        ui_file = self.ui_path_edit.text().strip()
        if ui_file:
            output_file = os.path.splitext(ui_file)[0] + ".py"
            os.system(f"pyuic5 -x '{ui_file}' -o '{output_file}'")
            self.status_label.setText(f"Status: Converted to {output_file}")
        else:
            self.status_label.setText("Status: No file selected!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # MainWindow = QtWidgets.QMainWindow()
    # ui = Ui_MainWindow()
    # ui.setupUi(MainWindow)
    # MainWindow.show()
    # sys.exit(app.exec_())
    window = MyMainWindow()
    window.show()
    sys.exit(app.exec_())
